---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  # NOTE: If you move either pem/kelvin for the first two spots
  # then you will have to update the ASAN/TSAN yaml-path
  # index below.
  - image: gcr.io/pixie-oss/pixie-dev/vizier/pem_image
    context: .
    bazel:
      target: //src/vizier/services/agent/pem:pem_image.tar
      args:
      - --compilation_mode=dbg
  - image: gcr.io/pixie-oss/pixie-dev/vizier/kelvin_image
    context: .
    bazel:
      target: //src/vizier/services/agent/kelvin:kelvin_image.tar
      args:
      - --compilation_mode=dbg
  - image: gcr.io/pixie-oss/pixie-dev/vizier/metadata_server_image
    context: .
    bazel:
      target: //src/vizier/services/metadata:metadata_server_image.tar
      args:
      - --compilation_mode=dbg
  - image: gcr.io/pixie-oss/pixie-dev/vizier/query_broker_server_image
    context: .
    bazel:
      target: //src/vizier/services/query_broker:query_broker_server_image.tar
      args:
      - --compilation_mode=dbg
  - image: gcr.io/pixie-oss/pixie-dev/vizier/cloud_connector_server_image
    context: .
    bazel:
      target: //src/vizier/services/cloud_connector:cloud_connector_server_image.tar
      args:
      - --compilation_mode=dbg
  - image: gcr.io/pixie-oss/pixie-dev/vizier/cert_provisioner_image
    context: .
    bazel:
      target: //src/utils/cert_provisioner:cert_provisioner_image.tar
      args:
      - --compilation_mode=dbg
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - k8s/vizier/persistent_metadata
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
- name: dbg
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
- name: opt
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
- name: jsyms
  patches:
  - op: add
    path: /deploy/kustomize/paths
    value:
    - k8s/vizier/jsyms
- name: heap
  patches:
  - op: add
    path: /deploy/kustomize/paths
    value:
    - k8s/vizier/heap_profile
- name: asan
  patches:
  - op: add
    path: /build/artifacts/0/bazel/args
    value:
    - --config=asan
  - op: add
    path: /build/artifacts/1/bazel/args
    value:
    - --config=asan
  - op: replace
    path: /deploy/kustomize/paths
    value:
    - k8s/vizier/sanitizer
- name: tsan
  patches:
  - op: add
    path: /build/artifacts/0/bazel/args
    value:
    - --config=tsan
  - op: add
    path: /build/artifacts/1/bazel/args
    value:
    - --config=tsan
  - op: replace
    path: /deploy/kustomize/paths
    value:
    - k8s/vizier/sanitizer
- name: etcd
  patches:
  - op: replace
    path: /deploy/kustomize/paths
    value:
    - k8s/vizier/etcd_metadata
